service: mrz
provider:
  name: aws
  runtime: nodejs8.10
  profile: me
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject*"
        - "s3:GetObject*"
      Resource: arn:aws:s3:::mrz-a-a-s
functions:
  validatemrz:
    handler: validatemrz.validatemrz